service:
  name: dev-woom-post-to-elasticsearch

frameworkVersion: '>=1.0.0 <2.0.0'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-2

functions:
  DynamoDBCallback:
    handler: dist/dynamoStreamHandler.handler
    events:
      - stream:
          arn: arn
          type: dynamodb
          batchSize: 100
    memorySize: 128
    timeout: 60